/**
 * Templates copied into a fresh `knowledge/` stash on first wiki-mode use.
 *
 * Inlined as TypeScript constants so they ship with the published bundle
 * (the build step is `tsc` — non-TS files are not copied to dist).
 */

export const SCHEMA_MD = `---
description: Rules that govern this knowledge wiki. Read this before ingesting, querying, or linting.
wikiRole: schema
---

# Knowledge wiki schema

This stash follows Andrej Karpathy's LLM Wiki pattern, adapted for akm.

## Layout

\`\`\`
knowledge/
  schema.md      this file (the rulebook)
  index.md       catalog of pages by category (regenerable)
  log.md         append-only ingest/query/lint log
  raw/           immutable ingested sources (slug filenames)
  <page>.md      LLM-authored entity / concept / question / note pages
  <topic>/<page>.md   optional subfolders
\`\`\`

## Page frontmatter

Every page should carry frontmatter so akm can index and link it:

\`\`\`yaml
---
description: one-sentence summary used in search and lint
pageKind: entity | concept | question | note | <your-custom-kind>
xrefs:
  - knowledge:other-page
sources:
  - raw/2026-04-the-source-doc.md
---
\`\`\`

### Extending the taxonomy

\`pageKind\` accepts any non-empty string. The four built-ins above are just
defaults. To introduce a new category (e.g. \`decision-record\`, \`glossary\`):

- **One-off:** write \`pageKind: decision-record\` on a page and carry on.
  Subsequent ingests will see the new kind and keep using it.
- **First-class:** add it to \`knowledge.pageKinds\` in your akm config so the
  LLM is told about it during ingest and \`index.md\` gets a matching section.

The \`raw/\` folder uses \`wikiRole: raw\` and is immutable. \`schema.md\`,
\`index.md\`, \`log.md\` carry their own \`wikiRole\` and follow special rules.

## Three operations

### Ingest
1. New source goes into \`raw/<slug>.md\`. Never overwrite.
2. Find related pages with \`akm search "<key terms>" --type knowledge\`.
3. For each related page, decide: append a section, leave alone, or note a
   contradiction. Update xrefs both ways.
4. Create new pages for entities/concepts the source introduces.
5. Append one entry to \`log.md\` describing what was assimilated.

### Query
1. Search the wiki with \`akm search "<question>"\`.
2. Read the top hits with \`akm show knowledge:<page>\`.
3. If the answer is valuable enough to keep, file it back as a new page or
   amend an existing one (this is itself an ingest with the answer as raw).

### Lint
1. Run \`akm lint\` periodically.
2. Resolve contradictions, link orphans, refresh stale claims, add missing
   cross-references.

## Hard rules
- \`raw/\` is immutable. Never edit ingested sources.
- Cross-references must point at pages that actually exist.
- Prefer appending to an existing page over duplicating one.
- Cite the source page id (e.g. \`raw/2026-04-foo.md\`) when copying claims.
`;

import { pageKindHeading } from "../knowledge-page-kinds";

/**
 * Generate the scaffolded `index.md` with a section for each configured
 * page kind. This lets the index reflect the active taxonomy: the built-in
 * defaults (entity/concept/question/note) plus anything the user has added
 * via `knowledge.pageKinds` in config.
 */
export function buildIndexMd(pageKinds: readonly string[]): string {
  const sections = pageKinds.map((kind) => `## ${pageKindHeading(kind)}\n\n_(none yet)_\n`).join("\n");
  return `---
description: Catalog of pages in this knowledge wiki, by category. Regenerate as new pages are added.
wikiRole: index
---

# Index

_This file is regenerated by ingest and lint runs. Manual edits are fine but may be reorganized. Add a new \`## Heading\` section any time you introduce a new page kind._

${sections}`;
}

export const LOG_MD = `---
description: Append-only log of ingest, query, and lint activity for this knowledge wiki.
wikiRole: log
---

# Log

_Newest entries at the top. Each entry: ISO date, operation, brief summary._
`;

export const SKILL_INGEST_MD = `---
description: Run akm import --llm to ingest a source into the knowledge wiki and update related pages.
---

# knowledge-ingest

Use this skill whenever the user wants to assimilate an article, paper, transcript, or note into their knowledge wiki.

## Steps

1. **Locate the source.** Confirm the file path or paste content into a temporary file.
2. **Preview the plan with --dry-run** when you want to review changes before they land:
   \`\`\`sh
   akm import <source> --llm --dry-run
   \`\`\`
3. **Inspect the proposed plan.** Look at: new pages, edits to existing pages, cross-references, summary.
4. **Apply (the default)** to write pages, update xrefs, reindex, and append to \`log.md\`:
   \`\`\`sh
   akm import <source> --llm
   \`\`\`
5. **Verify** with \`akm search\` that new pages are findable and \`akm show knowledge:<page>\` for each updated page.
6. **Never edit raw/.** If the LLM proposes to edit a raw file, reject the plan.

## Page kinds (categories)

The built-in page kinds are \`entity\`, \`concept\`, \`question\`, and \`note\`. You can add more at any time:

- **Ad hoc**: just set \`pageKind: <your-kind>\` in a page's frontmatter. Future ingests see the new kind in the taxonomy.
- **First-class**: declare the kinds in your akm config under \`knowledge.pageKinds\` so they appear as sections in \`index.md\` and are offered to the LLM as default choices.

Example config (\`~/.config/akm/config.json\`):

\`\`\`json
{
  "knowledge": {
    "pageKinds": ["decision-record", "retrospective", "glossary"]
  }
}
\`\`\`

## Guardrails

- Cross-references must already exist as pages. \`akm import\` enforces this; if the LLM hallucinates a ref, it will be silently dropped.
- Long sources (>8k chars) are truncated. For very large documents, split before ingesting.
- Apply is the default; the log entry is appended automatically unless you use \`--dry-run\`.
`;

export const SKILL_QUERY_MD = `---
description: Answer questions against the knowledge wiki and file good answers back as pages.
---

# knowledge-query

Use this skill when the user asks a question that should be answered from their knowledge wiki, not from raw sources directly.

## Steps

1. **Search first.** \`akm search "<the question>"\` to find candidate pages.
2. **Read the top hits.** \`akm show knowledge:<page>\` for each. Use \`akm show knowledge:<page> toc\` to scan, then \`section "<heading>"\` for depth.
3. **Compose the answer** primarily from the wiki. Cite raw sources only when the wiki points at them.
4. **File the answer back** if it's worth keeping:
   \`\`\`sh
   echo "Q: <question>\\n\\nA: <answer>" | akm import - --llm --name "q-<slug>"
   \`\`\`
   The pageKind for these is \`question\`.

## When not to file back

- The answer is purely procedural (e.g. "how do I run the tests").
- The answer is already covered by an existing page (just reference it).
`;

export const SKILL_LINT_MD = `---
description: Run akm lint to find contradictions, orphans, and missing cross-references in the knowledge wiki.
---

# knowledge-lint

Use this skill when the user asks to "tidy up", "audit", or "lint" their knowledge wiki, or on a regular cadence (e.g. weekly).

## Steps

1. **Run the audit.**
   \`\`\`sh
   akm lint
   \`\`\`
2. **Walk the findings.** Each finding has a kind (\`contradiction\`, \`orphan\`, \`stale\`, \`missing-xref\`, ...) and the affected refs.
3. **Discuss each finding with the user** before applying any fix that isn't trivial. Contradictions in particular need human judgement.
4. **Apply low-risk fixes** with:
   \`\`\`sh
   akm lint --fix
   \`\`\`
   This applies suggested fixes (mostly missing-xref additions) and logs each change.
5. **Append a lint entry** to log.md noting findings count and what was fixed.

## What lint will not do

- It will not delete pages.
- It will not rewrite contradictory claims — that requires a human decision and a fresh ingest.
`;
