#!/usr/bin/env bun
/**
 * Generate schemas/akm-config.json from the canonical Zod schema in
 * src/core/config/config-schema.ts. Run after editing the schema (or wire as a
 * pre-build step) so the published JSON Schema never drifts.
 *
 * Usage:
 *   bun scripts/gen-config-schema.ts          # write schemas/akm-config.json and the harness docs table
 *   bun scripts/gen-config-schema.ts --check  # exit non-zero if the file is stale
 */
import fs from "node:fs";
import path from "node:path";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  AkmConfigSchema,
  CURRENT_CONFIG_VERSION,
  EmbeddingConnectionConfigSchema,
  ImproveProcessConfigSchema,
  ImproveProfileConfigSchema,
  LlmProfileConfigSchema,
  RegistryConfigEntrySchema,
} from "../src/core/config/config-schema";
import { HARNESS_REGISTRY } from "../src/integrations/harnesses";

interface JsonSchema {
  $schema?: string;
  $id?: string;
  title?: string;
  description?: string;
  $defs?: Record<string, unknown>;
  [key: string]: unknown;
}

function generate(): JsonSchema {
  // Top-level schema with $defs for the named sub-schemas the drift test pins.
  // We generate each named sub-schema with its own name + target, then merge
  // them into a single $defs map.
  const targets = {
    AkmConfig: AkmConfigSchema,
    LlmProfileConfig: LlmProfileConfigSchema,
    EmbeddingConnectionConfig: EmbeddingConnectionConfigSchema,
    ImproveProcessConfig: ImproveProcessConfigSchema,
    ImproveProfileConfig: ImproveProfileConfigSchema,
    RegistryConfigEntry: RegistryConfigEntrySchema,
  } as const;

  const defs: Record<string, unknown> = {};
  for (const [name, schema] of Object.entries(targets)) {
    const partial = zodToJsonSchema(schema, {
      name,
      $refStrategy: "none",
      definitions: {},
    }) as Record<string, unknown>;
    // zod-to-json-schema (with `name`) returns `{ $ref: "#/definitions/<name>", definitions: { <name>: {...} } }`.
    // We unwrap to the inner schema object.
    const definitions = partial.definitions as Record<string, unknown> | undefined;
    if (definitions?.[name]) {
      defs[name] = definitions[name];
    } else {
      defs[name] = partial;
    }
  }

  const top = defs.AkmConfig as Record<string, unknown>;

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `https://itlackey.github.io/akm/schemas/akm-config.${CURRENT_CONFIG_VERSION}.json`,
    title: "AKM Configuration",
    description:
      "Configuration file for the akm CLI (Agent Knowledge Manager). Stored at " +
      "~/.config/akm/config.json (Linux/macOS) or %APPDATA%\\akm\\config.json " +
      "(Windows). Supports JSONC (JavaScript-style comments). Auto-generated " +
      "from src/core/config/config-schema.ts by scripts/gen-config-schema.ts — do NOT edit by hand.",
    ...top,
    $defs: defs,
  };
}

const HARNESS_DOC_START = "<!-- harness-table:start (generated by scripts/gen-config-schema.ts) -->";
const HARNESS_DOC_END = "<!-- harness-table:end -->";

/** The "Supported harnesses" docs table, derived from `HARNESS_REGISTRY`. */
export function renderHarnessTable(): string {
  const yes = (v: boolean): string => (v ? "yes" : "no");
  const rows = HARNESS_REGISTRY.map(
    (h) =>
      `| \`${h.id}\` | ${h.displayName} | ${h.profile ? `\`${h.profile.bin}\`` : "in-process"} | ${yes(h.capabilities.sessionLogs)} | ${yes(h.capabilities.modelWork)} | ${yes(h.capabilities.nativeAgent)} |`,
  );
  return [
    "| `platform` | Harness | Binary | Session logs | Model work | Native `agent` |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/** `configuration.md` with the generated harness table spliced between its markers. */
export function checkHarnessDocsDrift(): { upToDate: boolean; generated: string; existing: string } {
  const target = path.resolve(import.meta.dir, "..", "docs", "reference", "configuration.md");
  const existing = fs.readFileSync(target, "utf8");
  const start = existing.indexOf(HARNESS_DOC_START);
  const end = existing.indexOf(HARNESS_DOC_END);
  if (start < 0 || end < start) throw new Error(`${target} is missing the harness-table markers.`);
  const generated = `${existing.slice(0, start + HARNESS_DOC_START.length)}\n${renderHarnessTable()}\n${existing.slice(end)}`;
  return { upToDate: existing === generated, generated, existing };
}

/**
 * Compare the generated schema against the committed schemas/akm-config.json.
 * Pure function (no process.exit, no console output) so tests can call it
 * directly instead of spawning a subprocess.
 */
export function checkSchemaDrift(): { upToDate: boolean; generated: string; existing: string } {
  const repoRoot = path.resolve(import.meta.dir, "..");
  const target = path.join(repoRoot, "schemas", "akm-config.json");
  const generated = `${JSON.stringify(generate(), null, 2)}\n`;
  const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  return { upToDate: existing === generated, generated, existing };
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const repoRoot = path.resolve(import.meta.dir, "..");
  const target = path.join(repoRoot, "schemas", "akm-config.json");

  if (checkMode) {
    if (!checkSchemaDrift().upToDate || !checkHarnessDocsDrift().upToDate) {
      console.error(
        `schemas/akm-config.json or docs/reference/configuration.md is stale. Run \`bun scripts/gen-config-schema.ts\` to regenerate.`,
      );
      process.exit(1);
    }
    console.log("schemas/akm-config.json and the harness docs table are up to date.");
    return;
  }
  const generated = `${JSON.stringify(generate(), null, 2)}\n`;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, generated);
  console.log(`Wrote ${target}`);
  // `bun run build` runs this too, and a source tree without docs/ (the Docker install images) still builds.
  const docsPath = path.join(repoRoot, "docs", "reference", "configuration.md");
  if (fs.existsSync(docsPath)) fs.writeFileSync(docsPath, checkHarnessDocsDrift().generated);
}

if (import.meta.main) {
  main();
}
