// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Same-path re-export shim (#490 reorg, Phase 5). db.ts moved into
// indexer/db/db.ts as part of the by-pipeline-phase nesting. This shim keeps
// the historical indexer/db import path byte-diff-free for its high fan-in
// external importers (15+ sites). Explicit named re-exports only (never
// `export *`), one level; retire once aliases are universal.

export type {
  DbIndexedEntry,
  DbSearchResult,
  DbVecResult,
  EntryRefRow,
  FeedbackUtilityResult,
  IndexDirState,
  LlmCacheEntry,
  ScopedUtilityRow,
  UtilityScoreData,
  UtilityScoreRow,
} from "./db/db";
export {
  applyFeedbackToUtilityScore,
  bumpUtilityScoresBatch,
  clearStaleCacheEntries,
  closeDatabase,
  collectTagSetFromEntries,
  computeBodyHash,
  computeSourceHash,
  DB_VERSION,
  deleteEntriesByDir,
  deleteEntriesByIds,
  deleteEntriesByStashDir,
  deleteIndexDirState,
  deleteIndexDirStatesByStashDir,
  EMBEDDING_DIM,
  findEntryIdByRef,
  GRAPH_SCHEMA_VERSION,
  getAllEntries,
  getAllEntriesForEmbedding,
  getDerivedForParent,
  getEmbeddableEntryCount,
  getEmbeddingCount,
  getEntriesByDir,
  getEntryById,
  getEntryByRef,
  getEntryCount,
  getEntryFilePathById,
  getEntryIdByFilePath,
  getEntryRefRowsForStashRoot,
  getIndexDirState,
  getLlmCacheEntriesByRefs,
  getLlmCacheEntry,
  getMeta,
  getNeighborsByEntryId,
  getPositiveFeedbackCountsByIds,
  getRegistryIndexCache,
  getRetrievalCounts,
  getUtilityScore,
  getUtilityScoresByIds,
  getZeroResultSearches,
  HIGH_UTILITY_THRESHOLD,
  isVecAvailable,
  openDatabase,
  openExistingDatabase,
  rebuildFts,
  relinkUsageEvents,
  sanitizeFtsQuery,
  searchFts,
  searchVec,
  setMeta,
  UTILITY_REVIEW_THRESHOLD,
  upsertEmbedding,
  upsertEntry,
  upsertIndexDirState,
  upsertLlmCacheEntry,
  upsertRegistryIndexCache,
  upsertUtilityScore,
  upsertWorkflowDocument,
  warnIfVecMissing,
} from "./db/db";
